// The browser-side checks themselves, on small pages built in the test.

import { EXAMPLE_TOOLS } from "../../scripts/lib/attribution-patterns.ts";
import { attributionProblems, collectLiveDom, liveDomProblems, staticHostnameProblems } from "./dom-checks.ts";
import { expect, test } from "./fixtures.ts";

const toolA = EXAMPLE_TOOLS.find((t) => t.toLowerCase() === "cursor") as string;
const dictionaryName = EXAMPLE_TOOLS.find(
  (tool) => tool.startsWith("Co") && tool.endsWith("pilot"),
)?.toLowerCase() as string;
const PASSWORD_WITH_TLD = "9Qa.com#rX5?K+z8!mP2";

test.describe("data-generated", () => {
  test("a password-shaped value with a TLD passes the host-name scan inside data-generated", async ({ page }) => {
    const html = `<main><output data-generated>${PASSWORD_WITH_TLD}</output></main>`;
    expect(await staticHostnameProblems(page, "t.html", html)).toEqual([]);
  });

  test("the same value outside data-generated is reported", async ({ page }) => {
    const html = `<main><output>${PASSWORD_WITH_TLD}</output></main>`;
    expect((await staticHostnameProblems(page, "t.html", html)).length).toBeGreaterThan(0);
  });

  test("a dictionary name in a generated passphrase passes, but ordinary text fails", async ({ page }) => {
    await page.setContent(`<main><output data-generated>abacus-05-${dictionaryName}</output></main>`);
    expect(attributionProblems(await collectLiveDom(page))).toEqual([]);
    await page.setContent(`<main><output>abacus-05-${dictionaryName}</output></main>`);
    expect(attributionProblems(await collectLiveDom(page)).length).toBeGreaterThan(0);
  });

  test("catches credit text directly before a valid generated passphrase", async ({ page }) => {
    const phrase = `${dictionaryName}-05-abacus`;
    await page.setContent(`<main><p>Generated by <output data-generated>${phrase}</output></p></main>`);
    const findings = attributionProblems(await collectLiveDom(page));
    expect(findings.some((finding) => finding.includes(": authorship credit: "))).toBe(true);
    expect(await page.locator("output").textContent()).toBe(phrase);
  });

  test("a dictionary name in a valid passphrase with normal surrounding UI passes", async ({ page }) => {
    const phrase = `${dictionaryName}-05-abacus`;
    await page.setContent(
      `<main><h1>Passphrase</h1><p>Your passphrase: <output data-generated>${phrase}</output></p><button>Copy</button></main>`,
    );
    expect(attributionProblems(await collectLiveDom(page))).toEqual([]);
    expect(await page.locator("output").textContent()).toBe(phrase);
  });

  test("marking output does not exempt credits, attributes, comments or CSS", async ({ page }) => {
    await page.setContent(
      `<output data-generated title="${dictionaryName}">abacus-${dictionaryName}<!-- ${dictionaryName} --></output>`,
    );
    await page.addStyleTag({ content: `output::after{content:"${dictionaryName}"}` });
    expect(attributionProblems(await collectLiveDom(page)).length).toBeGreaterThanOrEqual(3);
    await page.setContent(`<output data-generated>Generated by ${dictionaryName}</output>`);
    expect(attributionProblems(await collectLiveDom(page)).length).toBeGreaterThan(0);
  });

  test("a credit inside data-generated is still caught", async ({ page }) => {
    await page.setContent(`<main><output data-generated>Generated by ${toolA}</output></main>`);
    expect(attributionProblems(await collectLiveDom(page)).length).toBeGreaterThan(0);
  });
});

test.describe("live DOM", () => {
  for (const tag of ["b", "span"]) {
    test(`catches a credit whose name is split across <${tag}>`, async ({ page }) => {
      const name = EXAMPLE_TOOLS.find((tool) => tool.startsWith("Cl") && tool.length === 6) as string;
      await page.setContent(`<p>Generated by ${name.slice(0, 3)}<${tag}>${name.slice(3)}</${tag}></p>`);
      expect(attributionProblems(await collectLiveDom(page)).length).toBeGreaterThan(0);
    });
  }

  test("valid output cannot hide identical non-output text and collection restores the DOM", async ({ page }) => {
    const phrase = `abacus-05-${dictionaryName}`;
    await page.setContent(`<output data-generated>${phrase}</output><p>${phrase}</p>`);
    expect(attributionProblems(await collectLiveDom(page)).length).toBeGreaterThan(0);
    expect(await page.locator("output").textContent()).toBe(phrase);
  });

  test("catches a credit generated by CSS ::after", async ({ page }) => {
    const escaped = `${toolA[0]}\\${(toolA.codePointAt(1) as number).toString(16)} ${toolA.slice(2)}`;
    await page.setContent(`<footer>x</footer>`);
    await page.addStyleTag({ content: `footer::after{content:"Generated by ${escaped}"}` });
    expect(attributionProblems(await collectLiveDom(page)).length).toBeGreaterThan(0);
  });

  test("catches a credit in ::before and ::marker", async ({ page }) => {
    await page.setContent(`<ul><li>x</li></ul><p>y</p>`);
    await page.addStyleTag({
      content: `p::before{content:"Made with ${toolA}"} li::marker{content:"Built with ${toolA}"}`,
    });
    expect(attributionProblems(await collectLiveDom(page)).length).toBeGreaterThanOrEqual(2);
  });

  test("reports a URL attribute that leaves the build", async ({ page }) => {
    await page.setContent(`<a href="../x.html">x</a>`);
    expect(liveDomProblems("index.html", await collectLiveDom(page))).toContain(
      'href="../x.html" on <a> leaves the build',
    );
  });

  test("allows only the named pointer properties on <html>, with bounded values and no !important", async ({
    page,
  }) => {
    await page.setContent('<main><p>x</p><input type="range"></main>');
    const problems = async () => liveDomProblems("index.html", await collectLiveDom(page));
    await page.evaluate(() => {
      const s = document.documentElement.style;
      s.setProperty("--px", "12.34%");
      s.setProperty("--pxn", "0.1234");
      document.querySelector<HTMLElement>("input")?.style.setProperty("--fill", "50%");
    });
    expect(await problems()).toEqual([]);
    // The bounds are exact: 100.00% and 1.0000 pass, nothing above them does.
    await page.evaluate(() => {
      document.documentElement.style.setProperty("--px", "100.00%");
      document.documentElement.style.setProperty("--pxn", "1.0000");
    });
    expect(await problems()).toEqual([]);
    for (const [property, value, expected] of [
      ["--px", "500%", /--px is 500%/],
      ["--px", "100.99%", /--px is 100.99%/],
      ["--px", "100.01%", /--px is 100.01%/],
      ["--pxn", "1.9999", /--pxn is 1.9999/],
      ["--pxn", "1.0001", /--pxn is 1.0001/],
      ["--px", "-1%", /--px is -1%/],
      ["--pxn", "7", /--pxn is 7/],
      ["--pxn", "0.5 1", /--pxn is 0.5 1/],
      ["--other", "1%", /sets --other/],
      ["background", "red", /sets background/],
      ["--fx-pointer", "none", /sets --fx-pointer/],
    ] as const) {
      await page.evaluate(([p, v]) => document.documentElement.style.setProperty(p, v), [property, value] as const);
      expect((await problems()).join("\n")).toMatch(expected);
      await page.evaluate((p) => document.documentElement.style.removeProperty(p), property);
    }
    await page.evaluate(() => document.documentElement.style.setProperty("--px", "1%", "important"));
    expect((await problems()).join("\n")).toMatch(/--px is !important/);
    await page.evaluate(() => document.documentElement.style.removeProperty("--px"));
    // An emptied attribute is still an attribute: the app removes it, so the gate refuses it.
    expect((await problems()).join("\n")).toMatch(/style attribute on <html> with no readable property/);
    await page.evaluate(() => document.documentElement.removeAttribute("style"));
    expect(await problems()).toEqual([]);
  });

  test("allows only --fill on range inputs and no inline style on anything else", async ({ page }) => {
    await page.setContent('<main><p>x</p><input type="range"><input type="number"><div></div></main>');
    const problems = async () => liveDomProblems("index.html", await collectLiveDom(page));
    await page.evaluate(() =>
      document.querySelector<HTMLElement>("input[type=range]")?.style.setProperty("--fill", "101%"),
    );
    expect((await problems()).join("\n")).toMatch(/--fill is 101%/);
    await page.evaluate(() =>
      document.querySelector<HTMLElement>("input[type=range]")?.style.setProperty("--fill", "40%"),
    );
    expect(await problems()).toEqual([]);
    await page.evaluate(() =>
      document.querySelector<HTMLElement>("input[type=range]")?.style.setProperty("--px", "1%"),
    );
    expect((await problems()).join("\n")).toMatch(/sets --px/);
    await page.evaluate(() => document.querySelector<HTMLElement>("input[type=range]")?.style.removeProperty("--px"));
    await page.evaluate(() =>
      document.querySelector<HTMLElement>("input[type=number]")?.style.setProperty("--fill", "40%"),
    );
    expect((await problems()).join("\n")).toMatch(/style attribute on <input>/);
    await page.evaluate(() => document.querySelector("input[type=number]")?.removeAttribute("style"));
    await page.evaluate(() => document.querySelector("div")?.setAttribute("style", "--px: 1%"));
    expect((await problems()).join("\n")).toMatch(/style attribute on <div>/);
  });

  test("a style attribute in the shipped HTML is refused, even with an allowed property", async ({ page }) => {
    for (const html of [
      '<html style="--px: 1%"><body><p>x</p></body></html>',
      '<main><input type="range" style="--fill: 1%"></main>',
      '<main><p style="color: red">x</p></main>',
    ]) {
      const found = await staticHostnameProblems(page, "t.html", html);
      expect(found.join("\n"), html).toMatch(/static content: style attribute on <(html|input|p)>/);
    }
    expect(await staticHostnameProblems(page, "t.html", "<main><p>x</p></main>")).toEqual([]);
  });
});
