// Combined-gate regressions: build a copy of the app with something bad
// injected, using the real Vite config, then run the real gates on the output
// (verify-dist, and the built-HTML browser checks) and expect each to fail for
// the injected reason. A clean copy must pass the same gates, so a failure can
// only come from the injection.
//
// Needs Chromium (run after `pnpm exec playwright install`). It starts the
// Playwright web servers, so it must not run alongside `pnpm test:e2e`.

import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { cp, mkdtemp, readFile, rm, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { after, before, describe, test } from "node:test";
import { promisify } from "node:util";
import { build } from "vite";
import { EXAMPLE_TOOLS } from "../../scripts/lib/attribution-patterns.ts";
import { config } from "../../src/config/validate.ts";

const run = promisify(execFile);
const ROOT = join(import.meta.dirname, "..", "..");
const toolA = EXAMPLE_TOOLS.find((t) => t.toLowerCase() === "cursor") as string;
/** The name with its second letter written as a CSS escape, e.g. "C\75 rsor". */
const cssEscaped = `${toolA[0]}\\${(toolA.codePointAt(1) as number).toString(16)} ${toolA.slice(2)}`;

let scratch: string;

before(async () => {
  // Shell syntax and spaces in the path: the build folder must reach the
  // Playwright web servers without ever being run as a command.
  scratch = await mkdtemp(join(resolve(tmpdir()), "passgen gate $(touch pwned) "));
});

after(async () => {
  for (const dir of [ROOT, scratch, resolve(tmpdir())]) {
    await assert.rejects(stat(join(dir, "pwned")), `a command in the path ran in ${dir}`);
  }
  await rm(scratch, { recursive: true, force: true });
});

async function buildFixture(name: string, inject: { css?: string; body?: string } = {}): Promise<string> {
  const dir = join(scratch, name);
  for (const entry of ["index.html", "src", "public", "vendor"])
    await cp(join(ROOT, entry), join(dir, entry), { recursive: true });
  if (inject.css !== undefined) {
    const styles = join(dir, "src", "styles.css");
    await writeFile(styles, `${await readFile(styles, "utf8")}\n${inject.css}\n`);
  }
  if (inject.body !== undefined) {
    const index = join(dir, "index.html");
    await writeFile(index, (await readFile(index, "utf8")).replace("</main>", `</main>\n    ${inject.body}`));
  }
  await build({ root: dir, configFile: join(ROOT, "vite.config.ts"), logLevel: "silent" });
  return join(dir, "dist");
}

async function gate(command: string, args: string[], env: Record<string, string> = {}) {
  try {
    const { stdout, stderr } = await run(command, args, { cwd: ROOT, env: { ...process.env, ...env } });
    return { code: 0, output: stdout + stderr };
  } catch (err) {
    const e = err as { code: number; stdout: string; stderr: string };
    return { code: e.code, output: e.stdout + e.stderr };
  }
}

const verifyDist = (dist: string) => gate(process.execPath, [join(ROOT, "scripts", "verify-dist.ts"), "--dir", dist]);

const builtHtmlBrowserChecks = (dist: string) =>
  gate(
    "pnpm",
    [
      "exec",
      "playwright",
      "test",
      "tests/e2e/built-html.spec.ts",
      "--project=chromium",
      "--reporter=line",
      `--output=${join(dist, "..", "test-results")}`,
    ],
    { PASSGEN_DIST: dist, PASSGEN_E2E_PROJECTS: "" },
  );

describe("combined gates", { timeout: 300_000 }, () => {
  test("a clean build passes verify-dist and the browser checks", async () => {
    const dist = await buildFixture("clean");
    const verify = await verifyDist(dist);
    assert.equal(verify.code, 0, verify.output);
    const browser = await builtHtmlBrowserChecks(dist);
    assert.equal(browser.code, 0, browser.output);
  });

  for (const [label, css] of [
    ["root-relative path through the old placeholder", "body{background-image:url(/__dist__/outside.png)}"],
    [
      "traversal back into a same-named folder",
      "@media (min-width:2000px){body{background-image:url(../../__dist__/outside.png)}}",
    ],
    ["traversal in @supports", "@supports (display:grid){body{background:url(../../outside.png)}}"],
    ["traversal in image-set()", 'body{background-image:image-set("../../outside.png" 1x)}'],
  ] as const) {
    test(`verify-dist fails on a CSS URL out of the build: ${label}`, async () => {
      const verify = await verifyDist(await buildFixture(`css-${label.replace(/\W+/g, "-")}`, { css }));
      assert.notEqual(verify.code, 0, verify.output);
      assert.match(verify.output, /CSS URL leaves the build/);
    });
  }

  test("a credit wrapped inside an HTML comment survives the build and fails verify-dist", async () => {
    const dist = await buildFixture("html-comment-credit", {
      body: `<!--\n    This file was generated by\n    ${toolA}.\n    -->`,
    });
    assert.match(await readFile(join(dist, "index.html"), "utf8"), /<!--/);
    const verify = await verifyDist(dist);
    assert.notEqual(verify.code, 0, verify.output);
    assert.match(verify.output, /index\.html.*attribution: .*authorship credit/);
  });

  test("the configured repository link written as page text, or another link, fails verify-dist and the browser checks", async () => {
    const dist = await buildFixture("link-as-text", {
      body: `<p>${config.links.repoUrl}</p>\n    <a href="${config.links.repoUrl}/releases">Releases</a>`,
    });
    const verify = await verifyDist(dist);
    assert.notEqual(verify.code, 0, verify.output);
    assert.match(verify.output, /index\.html: URL with a scheme/);
    const browser = await builtHtmlBrowserChecks(dist);
    assert.notEqual(browser.code, 0, browser.output);
    assert.match(browser.output, /has no host names in its static content/);
    assert.match(browser.output, /follows the markup and URL rules/);
  });

  test("a credit generated by CSS fails verify-dist and the browser checks", async () => {
    const dist = await buildFixture("css-credit", {
      css: `footer::after{content:"Generated by ${cssEscaped}"}`,
      body: "<footer>PassGen</footer>",
    });
    const verify = await verifyDist(dist);
    assert.notEqual(verify.code, 0, verify.output);
    assert.match(verify.output, /attribution: .*authorship credit/);
    const browser = await builtHtmlBrowserChecks(dist);
    assert.notEqual(browser.code, 0, browser.output);
    assert.match(browser.output, /credits no tool anywhere/);
    assert.match(browser.output, /authorship credit/);
  });
});
