// Owner rule: nothing in this repository credits a tool, model, assistant or
// vendor for writing it. Not in commits, pull requests, code, docs or the site.
//
// This file is the deny list, so it necessarily names them. It holds data only
// and is the one file scripts/check-attribution.ts does not scan.

/** The explicit dictionary data exceptions; adding a name requires separate review. */
export const DICTIONARY_COLLISIONS: readonly string[] = ["copilot", "codex", "cursor", "llama"];

/**
 * Names that have no ordinary meaning in this codebase: flagged anywhere.
 * Each entry is a regular expression source, matched case-insensitively on word boundaries.
 */
export const UNAMBIGUOUS_NAMES: readonly string[] = [
  "omnigent",
  "claude",
  "anthropic",
  "openai",
  "chatgpt",
  "gpt(?:-?\\d[\\w.]*)?",
  "codex",
  "copilot",
  "gemini",
  "antigravity",
  "open[\\s-]?code",
  "windsurf",
  "deepseek",
];

/**
 * Names that are also ordinary words (the CSS cursor, the number pi, …):
 * flagged only in an authorship context such as "generated by" or a co-author trailer.
 */
export const AMBIGUOUS_NAMES: readonly string[] = [
  "cursor",
  "pi",
  "hermes",
  "polly",
  "devin",
  "aider",
  "qwen",
  "llama",
  "mistral",
  "grok",
  "kiro",
  "cline",
  "jules",
];

/** Generic words for an automated author. */
export const GENERIC_AUTHORS: readonly string[] = [
  "ai",
  "llm",
  "assistant",
  "agent",
  "model",
  "bot",
  "chatbot",
  "machine",
];

/** Spellings the tests use, covering every name above. */
export const EXAMPLE_TOOLS: readonly string[] = [
  "Omnigent",
  "Claude",
  "Claude Code",
  "Anthropic",
  "OpenAI",
  "ChatGPT",
  "GPT-6",
  "Codex",
  "Copilot",
  "Gemini",
  "Antigravity",
  "OpenCode",
  "Windsurf",
  "DeepSeek",
  "Cursor",
  "Pi",
  "Hermes",
  "Polly",
  "Devin",
  "Aider",
  "Qwen",
  "Llama",
  "Mistral",
  "Grok",
  "Kiro",
  "Cline",
  "Jules",
];

export const AUTHORSHIP_VERBS: readonly string[] = [
  "generated",
  "built",
  "made",
  "written",
  "created",
  "powered",
  "assisted",
  "authored",
  "co-authored",
  "coded",
  "developed",
  "produced",
  "drafted",
  "crafted",
];

const ANY_TOOL = [...UNAMBIGUOUS_NAMES, ...AMBIGUOUS_NAMES, ...GENERIC_AUTHORS].join("|");
const ARTICLE = "(?:(?:the|an?|our|my)\\s+)?";

const IDENTIFIER_SEPARATOR = "[_-]*";
const IDENTIFIER_VERBS = AUTHORSHIP_VERBS.map((verb) => verb.replaceAll("-", IDENTIFIER_SEPARATOR)).join("|");
const NAMED_TOOL = [...UNAMBIGUOUS_NAMES, ...AMBIGUOUS_NAMES]
  .map((name) => (name === "claude" ? "claude(?:[_-]?code)?" : name))
  .join("|");
const IDENTIFIER_TOOL = `(?:${NAMED_TOOL})`;
// Short names easily occur as ordinary identifier prefixes. They need an
// explicit separator for any tool-first credit; longer names permit camel case.
const TOOL_FIRST = [...UNAMBIGUOUS_NAMES, ...AMBIGUOUS_NAMES]
  .map((name) => {
    const tool = name === "claude" ? "claude(?:[_-]?code)?" : name;
    return `(?:${tool})${name.length <= 2 ? "[_-]+" : IDENTIFIER_SEPARATOR}`;
  })
  .join("|");
export const ATTRIBUTION_PATTERNS: ReadonlyArray<readonly [string, RegExp]> = [
  ["assistant or vendor name", new RegExp(`\\b(?:${UNAMBIGUOUS_NAMES.join("|")})\\b`, "i")],
  [
    "authorship credit",
    new RegExp(
      `\\b(?:${AUTHORSHIP_VERBS.join("|")})\\s+(?:\\w+\\s+)?(?:by|with|using|via|through|in|from)\\s+${ARTICLE}(?:help\\s+(?:of|from)\\s+${ARTICLE})?(?:${ANY_TOOL})\\b`,
      "i",
    ),
  ],
  [
    "credit to a tool",
    new RegExp(
      `\\b(?:with\\s+(?:the\\s+)?help\\s+(?:of|from)|thanks\\s+to|courtesy\\s+of)\\s+${ARTICLE}(?:${ANY_TOOL})\\b`,
      "i",
    ),
  ],
  ["AI-generated label", /\b(?:ai|llm)[- ](?:generated|assisted|written|authored|built)\b/i],
  ["co-author trailer naming a tool", new RegExp(`^\\s*co-authored-by:.*\\b(?:${ANY_TOOL})\\b`, "im")],
  ["bot co-author trailer", /^\s*co-authored-by:.*<[^>]*noreply@(?!users\.noreply\.github\.com)[^>]*>/im],
  [
    "identifier authorship credit",
    new RegExp(
      `\\b(?:(?:${IDENTIFIER_VERBS})${IDENTIFIER_SEPARATOR}(?:by|with|using|via|from)${IDENTIFIER_SEPARATOR}${IDENTIFIER_TOOL}[a-z0-9_]*|co_*authored_*by|(?:${TOOL_FIRST})(?:credit|attribution|author)[a-z0-9_]*|(?:${TOOL_FIRST})(?:${IDENTIFIER_VERBS})(?![a-z0-9])[a-z0-9_]*)\\b`,
      "i",
    ),
  ],
  [
    "key-value authorship credit",
    new RegExp(`\\b(?:generated[_-]?by|credit|generator)\\s*[:=]\\s*["'](?:${NAMED_TOOL})\\b`, "i"),
  ],
  [
    "generator metadata credit",
    new RegExp(
      "<meta\\b(?=[^>]*\\bname\\s*=\\s*[\"']generator[\"'])(?=[^>]*\\bcontent\\s*=\\s*[\"'](?:" +
        NAMED_TOOL +
        ")\\b)[^>]*>",
      "i",
    ),
  ],
  ["robot emoji", /\u{1F916}/u],
];

export const PATTERNS_FILE = "scripts/lib/attribution-patterns.ts";
