// Full static-site examples; security header values stay in the included snippets.
import { SECURITY_HEADERS } from "../../security/headers.ts";

const GENERATED_SITE = "# Generated by pnpm headers:gen. Edit scripts/lib/site-configs.ts instead.";

/** Container paths; the Dockerfile copies the generated files to exactly these. */
export const CONTAINER_PATHS = {
  config: "/etc/passgen",
  root: "/srv/passgen",
  headers: "/etc/passgen/passgen-headers.conf",
  site: "/etc/passgen/passgen-site.conf",
  mimeTypes: "/etc/passgen/mime.types",
  port: 8080,
} as const;

/**
 * The one nginx server template. The shipped example and the container image
 * differ only in their listener lines, transport lines and header include path.
 */
export function nginxSite(options: {
  notes: readonly string[];
  listen: readonly string[];
  transport: readonly string[];
  headers: string;
}): string {
  const include = `include ${options.headers};`;
  const indent = (lines: readonly string[]) => lines.map((line) => `    ${line}\n`).join("");
  return `${GENERATED_SITE}
${options.notes.map((note) => `# ${note}\n`).join("")}map $status $passgen_asset_cache {
    default "no-cache";
    200 "public, max-age=31536000, immutable";
    304 "public, max-age=31536000, immutable";
}
server {
${indent(options.listen)}    root /srv/passgen;
    index index.html;
    server_tokens off;
    autoindex off;
    ssi off;
    disable_symlinks on;
${indent(options.transport)}    if ($request_method !~ ^(GET|HEAD)$) { return 405; }
    ${include}
    add_header Cache-Control "no-cache" always;
    # Explicit errors prevent inherited error_page routes from proxying elsewhere.
    recursive_error_pages off;
    error_page 403 =403 @forbidden;
    error_page 404 =404 @missing;
    error_page 405 =405 @method;
    location @forbidden {
        ${include}
        add_header Cache-Control "no-cache" always;
        return 403;
    }
    location @missing {
        ${include}
        add_header Cache-Control "no-cache" always;
        return 404;
    }
    location @method {
        ${include}
        add_header Cache-Control "no-cache" always;
        return 405;
    }
    location ~* (^|/)\\.|\\.(php[0-9]*|phtml|phar|cgi|pl|py|sh|shtml|map)(/|$)|^/(icons|cgi-bin)(/|$)|^/poweredby\\.png$ {
        ${include}
        add_header Cache-Control "no-cache" always;
        return 403;
    }
    location = / {
        ${include}
        add_header Cache-Control "no-cache" always;
        limit_except GET { deny all; }
        try_files /index.html =404;
    }
    location ~ "^/assets/[^/]+-[A-Za-z0-9_-]{8,}\\.(js|css|woff2|png|svg|ico)$" {
        ${include}
        add_header Cache-Control $passgen_asset_cache always;
        limit_except GET { deny all; }
        try_files $uri =404;
    }
    location / {
        ${include}
        add_header Cache-Control "no-cache" always;
        limit_except GET { deny all; }
        try_files $uri =404;
    }
    # No alias, rewrite to another application, fastcgi, CGI, SSI or proxy_pass.
}
`;
}

/** Configuration baked into the official container image, keyed by path under deploy/container/. */
export function renderContainerConfigs(): Map<string, string> {
  const { headers, mimeTypes, port, site } = CONTAINER_PATHS;
  return new Map([
    [
      "passgen-site.conf",
      nginxSite({
        notes: [
          "Official container image: plain HTTP behind an HTTPS proxy, any host name.",
          "Never redirect on the connection scheme here; TLS terminates at the proxy.",
        ],
        listen: [`listen ${port} default_server;`, "server_name _;"],
        transport: ["absolute_redirect off;"],
        headers,
      }),
    ],
    [
      "nginx.conf",
      `${GENERATED_SITE}
# Official container image: runs as UID/GID 101 with a read-only root filesystem.
# Only /tmp is written: the PID file and nginx's temporary directories.
daemon off;
worker_processes auto;
pid /tmp/nginx.pid;
error_log /dev/stderr notice;
events {
    worker_connections 1024;
}
http {
    include ${mimeTypes};
    default_type application/octet-stream;
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';
    # The image's own health check is not logged; only it can connect from loopback.
    map "$remote_addr $http_user_agent" $passgen_access_log {
        "127.0.0.1 passgen-healthcheck" 0;
        default 1;
    }
    access_log /dev/stdout main if=$passgen_access_log;
    sendfile on;
    keepalive_timeout 65;
    server_tokens off;
    client_body_temp_path /tmp/client_temp;
    proxy_temp_path /tmp/proxy_temp;
    fastcgi_temp_path /tmp/fastcgi_temp;
    uwsgi_temp_path /tmp/uwsgi_temp;
    scgi_temp_path /tmp/scgi_temp;
    include ${site};
}
`,
    ],
  ]);
}

export function renderSiteConfigs(): Map<string, string> {
  const apacheUnsets = SECURITY_HEADERS.map((h) => `    Header onsuccess unset ${h.name}`).join("\n");
  return new Map([
    [
      "apache/passgen-site.conf",
      String.raw`# Generated by pnpm headers:gen. Edit scripts/lib/site-configs.ts instead.
# Replace example.com, certificate paths and /srv/passgen before use.
# Requires mod_ssl, mod_headers, mod_authz_core and mod_mime.
# Use an existing TLS listener; configure ServerTokens Prod globally.
<VirtualHost *:443>
    ServerName example.com
    DocumentRoot /srv/passgen
    ServerSignature Off
    TraceEnable Off
    DirectoryIndex index.html
    ErrorDocument 404 "Not found"
    ErrorDocument 403 "Forbidden"
    ErrorDocument 405 "Method not allowed"
    FileETag None

    SSLEngine On
    SSLCertificateFile /etc/pki/tls/certs/example.com.pem
    SSLCertificateKeyFile /etc/pki/tls/private/example.com.key
    <IfModule proxy_module>
        ProxyRequests Off
        ProxyPassInherit Off
        ProxyPass "/" "!"
    </IfModule>
    <IfModule rewrite_module>
        RewriteEngine Off
    </IfModule>

    # Filesystem baseline only: inherited, more-specific Alias grants can override it.
    # The REQUEST_FILENAME condition below is the mandatory final containment check.
    <Directory "/">
        AllowOverride None
        Options None
        Require all denied
    </Directory>
    <Directory "/srv/passgen">
        AllowOverride None
        Options None
        Require all granted
        AcceptPathInfo Off
        FallbackResource disabled
    </Directory>
    <Location "/">
        # Location merges after FilesMatch, overriding global PHP/FastCGI handlers.
        SetHandler default-handler
        AuthMerging And
        <RequireAll>
            Require expr "%{HTTP_HOST} =~ m#(?i)^example[.]com(?::443)?$#"
            Require method GET HEAD
            Require expr "%{REQUEST_FILENAME} =~ m#^/srv/passgen(/|$)#"
        </RequireAll>
    </Location>
    <LocationMatch "(?i)(^|/)\.|\.(php[0-9]*|phtml|phar|cgi|pl|py|sh|shtml|map)(/|$)">
        Require all denied
    </LocationMatch>
    RemoveHandler .php .phtml .phar .cgi .pl .py .sh .shtml .html .js .css
    RemoveOutputFilter .html .shtml
    AddType text/html .html
    AddType text/javascript .js
    AddType text/css .css
    AddType application/json .json
    AddType application/manifest+json .webmanifest
    AddType image/svg+xml .svg
    AddType image/png .png
    AddType image/x-icon .ico
    AddType font/woff2 .woff2
    AddType text/plain .txt
    AddDefaultCharset UTF-8

    Header onsuccess unset Cache-Control
    Header always set Cache-Control "no-cache"
    <FilesMatch "-[A-Za-z0-9_-]{8,}\.(js|css|woff2|png|svg|ico)$">
        Header always set Cache-Control "public, max-age=31536000, immutable" "expr=%{REQUEST_STATUS} == 200 || %{REQUEST_STATUS} == 304"
    </FilesMatch>
    <Files "index.html">
        Header always set Cache-Control "no-cache"
    </Files>
    # Clear the other header table to avoid duplicate policies.
${apacheUnsets}
    Include /etc/httpd/passgen/passgen-headers.conf
</VirtualHost>
`,
    ],
    [
      "nginx/passgen-site.conf",
      nginxSite({
        notes: [
          "Replace example.com, certificate paths and /srv/passgen before use.",
          "Include inside http {}, with the standard mime.types table.",
        ],
        listen: ["listen 443 ssl;", "listen [::]:443 ssl;", "server_name example.com;"],
        transport: [
          "ssl_certificate /etc/pki/tls/certs/example.com.pem;",
          "ssl_certificate_key /etc/pki/tls/private/example.com.key;",
        ],
        headers: "/etc/nginx/passgen/passgen-headers.conf",
      }),
    ],
    [
      "caddy/Caddyfile",
      String.raw`# Generated by pnpm headers:gen. Edit scripts/lib/site-configs.ts instead.
# Replace example.com, certificate paths and /srv/passgen before use.
# Import into your Caddyfile; use a publicly trusted certificate.
example.com {
	tls /etc/pki/tls/certs/example.com.pem /etc/pki/tls/private/example.com.key
	root * /srv/passgen
	@bad_method not method GET HEAD
	@blocked path_regexp blocked (?i)(^|/)\.|\.(php[0-9]*|phtml|phar|cgi|pl|py|sh|shtml|map)(/|$)|^/(icons|cgi-bin)(/|$)|^/poweredby\.png$
	@hashed path_regexp hashed ^/assets/[^/]+-[A-Za-z0-9_-]{8,}\.(js|css|woff2|png|svg|ico)$
	route {
		import /etc/caddy/passgen/passgen-headers.caddy
		header -Server
		header Cache-Control "no-cache"
		error @bad_method "Method not allowed" 405
		error @blocked "Forbidden" 403
		header @hashed Cache-Control "public, max-age=31536000, immutable"
		file_server {
			index index.html
			# No browse. Publish only verified regular files; no payload symlinks.
		}
	}
	handle_errors {
		import /etc/caddy/passgen/passgen-headers.caddy
		header -Server
		header Cache-Control "no-cache"
		respond "Request refused" {err.status_code}
	}
}
`,
    ],
  ]);
}
