// Fixtures are built from the exported lists, so this file names no tool itself.

import assert from "node:assert/strict";
import { describe, test } from "node:test";
import {
  AMBIGUOUS_NAMES,
  ATTRIBUTION_PATTERNS,
  AUTHORSHIP_VERBS,
  EXAMPLE_TOOLS,
  GENERIC_AUTHORS,
  UNAMBIGUOUS_NAMES,
} from "../../scripts/lib/attribution-patterns.ts";

const flagged = (text: string) => ATTRIBUTION_PATTERNS.some(([, pattern]) => pattern.test(text));

describe("attribution patterns", () => {
  test("every listed name has an example spelling", () => {
    for (const name of [...UNAMBIGUOUS_NAMES, ...AMBIGUOUS_NAMES]) {
      const pattern = new RegExp(`^(?:${name})\\b`, "i");
      assert.ok(
        EXAMPLE_TOOLS.some((tool) => pattern.test(tool)),
        name,
      );
    }
  });

  for (const tool of EXAMPLE_TOOLS) {
    for (const credit of [
      `Generated by ${tool}`,
      `Built with ${tool}`,
      `Made with ${tool}`,
      `Written by ${tool}`,
      `Created using ${tool}`,
      `Powered by ${tool}`,
      `Assisted by ${tool}`,
      `Co-authored with the help of ${tool}`,
      `generated with ${tool}.`,
      `This page was built entirely with ${tool}`,
      `Thanks to ${tool}`,
      `Co-authored-by: ${tool} <dev@example.invalid>`,
      `<footer>Made with ${tool}</footer>`,
      `// Generated by ${tool}`,
    ]) {
      test(`flags "${credit}"`, () => {
        assert.ok(flagged(credit), credit);
      });
    }
  }

  for (const verb of AUTHORSHIP_VERBS) {
    test(`flags "${verb} by" with a generic author`, () => {
      for (const generic of ["an AI", "an LLM", "the assistant", "an agent", "a bot"]) {
        assert.ok(flagged(`${verb} by ${generic}`), `${verb} by ${generic}`);
      }
    });
  }

  test("covers the generic authors", () => {
    assert.ok(GENERIC_AUTHORS.length > 0);
    assert.ok(flagged(`${(GENERIC_AUTHORS[0] as string).toUpperCase()}-generated`));
    assert.ok(flagged("Co-authored-by: Helper <noreply@example.invalid>"));
    assert.ok(flagged("\u{1F916} done"));
  });

  for (const ordinary of [
    "cursor: pointer;",
    "button { cursor: not-allowed; }",
    "const area = Math.PI * r * r;",
    "pi = 3.14159",
    "The cursor moves to the next field.",
    "Hermes is a JavaScript engine name we do not use.",
    "Built with Vite and TypeScript.",
    "Generated from security/headers.ts by `pnpm headers:gen`.",
    "Co-authored-by: Pat Example <pat@example.invalid>",
    "The model of the page is a static folder.",
    "Agents follow AGENTS.md.",
    "Copied to clipboard",
  ]) {
    test(`allows "${ordinary}"`, () => {
      assert.ok(!flagged(ordinary), ordinary);
    });
  }
});
