// End-to-end tests of the attribution scanner: scanText() directly, then
// scripts/check-attribution.ts run in a throwaway git repository. Tool names
// come from the exported lists, so this file names none itself.

import assert from "node:assert/strict";
import { execFile, execFileSync } from "node:child_process";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { after, before, describe, test } from "node:test";
import { promisify } from "node:util";
import { EXAMPLE_TOOLS } from "../../scripts/lib/attribution-patterns.ts";
import { scanText } from "../../scripts/lib/attribution-scan.ts";

const run = promisify(execFile);
const SCRIPT = join(import.meta.dirname, "..", "..", "scripts", "check-attribution.ts");
const tool = (name: string) => {
  const found = EXAMPLE_TOOLS.find((t) => t.toLowerCase() === name);
  assert.ok(found, name);
  return found;
};
const toolA = tool("cursor");
const toolB = tool("pi");
/** Inserts markup in the middle of a name: split("Name", "<b>", "</b>") gives "Na<b>me</b>". */
const split = (name: string, open: string, close = "") => {
  const half = Math.ceil(name.length / 2);
  return `${name.slice(0, half)}${open}${name.slice(half)}${close}`;
};

describe("scanText", () => {
  const cases: Array<[string, string, number]> = [
    ["credit split across lines", `Intro\n\nGenerated by\n${toolA}\n`, 3],
    ["Markdown emphasis", `# Title\nGenerated by **${toolA}**\n`, 2],
    ["Markdown underscores and code", `Built with _${toolB}_ and \`${toolA}\``, 1],
    ["Markdown link", `Made with [${toolA}](./x)`, 1],
    ["HTML inline tags", `<footer>Generated by <b>${toolB}</b></footer>`, 1],
    ["HTML across lines", `<footer>\n  Generated by\n  <a href="./x">${toolB}</a>\n</footer>`, 2],
    ["string concatenation", `const s = "Generated by " +\n  "${toolA}";`, 1],
    ["comment block", `/*\n * Written with the help of\n * ${toolB}\n */`, 2],
    ["collapsed whitespace", `Powered   by\t\t${toolA}`, 1],
    ["word split by <b>", `<footer>Generated by ${split(toolA, "<b>", "</b>")}</footer>`, 1],
    ["word split by <span>", `<p>Made with ${split(toolA, '<span class="x">', "</span>")}</p>`, 1],
    ["word split by a comment", `Built with ${split(toolA, "<!-- -->")}`, 1],
    ["word split by &shy;", `Generated by ${split(toolA, "&shy;")}`, 1],
    ["word split by &#8203;", `Generated by ${split(toolA, "&#8203;")}`, 1],
    ["word split by a soft hyphen", `Generated by ${split(toolA, "\u00AD")}`, 1],
    ["word split by a zero-width space", `Generated by ${split(toolA, "\u200B")}`, 1],
    ["word split by a word joiner", `Powered by ${split(toolB, "\u2060")}`, 1],
    ["word split by a BOM", `Powered by ${split(toolA, "\uFEFF")}`, 1],
    ["credit wrapped inside an HTML comment", `<p>x</p>\n<!--\nThis file was generated by\n${toolA}.\n-->`, 2],
    ["credit wrapped inside a CSS block comment", `a{}\n/*\n * This file was generated by\n * ${toolA}.\n */`, 2],
    ["credit wrapped across // lines", `x = 1;\n// This file was generated by\n// ${toolA}.\n`, 2],
    ["credit wrapped across # lines", `key: 1\n# This file was generated by\n# ${toolB}.\n`, 2],
    ["credit wrapped in plain Markdown prose", `# Title\n\nThis file was generated by\n${toolA}.\n`, 3],
    ["credit in an unterminated comment", `<p>x</p>\n<!-- note\ngenerated by\n${toolA}`, 2],
  ];
  for (const [label, text, line] of cases) {
    test(`catches ${label} and reports line ${line}`, () => {
      const findings = scanText("f.md", text);
      assert.ok(findings.length > 0, label);
      assert.ok(
        findings.some((f) => f.startsWith(`f.md:${line}:`)),
        findings.join("\n"),
      );
    });
  }

  for (const ordinary of [
    "button {\n  cursor: pointer;\n}\n",
    "const area = Math.PI * r * r;\n// pi is about 3.14159\n",
    "Generated from security/headers.ts by `pnpm headers:gen`.",
    "<p>Built with Vite</p>",
    "The cursor\nmoves to the next field.",
    "<p>Built</p><p>with</p><p>care</p>",
    "<div>Generated by</div><div>hand</div>",
  ]) {
    test(`allows ${JSON.stringify(ordinary.slice(0, 30))}`, () => {
      assert.deepEqual(scanText("f", ordinary), []);
    });
  }
});

describe("check-attribution script", () => {
  let repo: string;
  const gitIn = (...args: string[]) => execFileSync("git", args, { cwd: repo, encoding: "utf8" });

  before(async () => {
    repo = await mkdtemp(join(resolve(tmpdir()), "passgen-attribution-"));
    gitIn("init", "-q", "-b", "main");
    gitIn("config", "user.name", "Test");
    gitIn("config", "user.email", "test@example.invalid");
    await writeFile(join(repo, "README.md"), "# Clean\n");
    gitIn("add", "-A");
    gitIn("commit", "-q", "-m", "chore: start");
  });

  after(async () => {
    await rm(repo, { recursive: true, force: true });
  });

  async function check(env: Record<string, string> = {}): Promise<{ code: number; output: string }> {
    try {
      const { stdout, stderr } = await run(process.execPath, [SCRIPT], {
        cwd: repo,
        env: { ...process.env, ATTRIBUTION_RANGE: "HEAD", PR_TITLE: "", PR_BODY: "", ...env },
      });
      return { code: 0, output: stdout + stderr };
    } catch (err) {
      const e = err as { code: number; stdout: string; stderr: string };
      return { code: e.code, output: e.stdout + e.stderr };
    }
  }

  test("passes a clean repository", async () => {
    assert.equal((await check()).code, 0);
  });

  test("fails on a credit in a tracked file, naming file and line", async () => {
    await writeFile(join(repo, "page.html"), `<main></main>\n<footer>Generated by <b>${toolB}</b></footer>\n`);
    gitIn("add", "page.html");
    const res = await check();
    gitIn("rm", "-q", "-f", "page.html");
    assert.notEqual(res.code, 0);
    assert.match(res.output, /page\.html:2:/);
  });

  test("fails on a credit in a new, untracked file", async () => {
    await writeFile(join(repo, "notes.md"), `Generated by\n**${toolA}**\n`);
    const res = await check();
    await rm(join(repo, "notes.md"));
    assert.notEqual(res.code, 0);
    assert.match(res.output, /notes\.md:1:/);
  });

  test("fails on a credit in a commit message", async () => {
    gitIn("commit", "-q", "--allow-empty", "-m", "feat: thing", "-m", `Built with\n${toolA}`);
    const res = await check({ ATTRIBUTION_RANGE: "HEAD~1..HEAD" });
    gitIn("reset", "-q", "--hard", "HEAD~1");
    assert.notEqual(res.code, 0);
    assert.match(res.output, /commit [0-9a-f]{12}:/);
  });

  test("fails on a credit in the PR title or body", async () => {
    assert.notEqual((await check({ PR_TITLE: `feat: page, made with ${toolB}` })).code, 0);
    const body = await check({ PR_BODY: `## Summary\n\nGenerated by **${toolA}**` });
    assert.notEqual(body.code, 0);
    assert.match(body.output, /PR body:3:/);
  });
});
