import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { test } from "node:test";
import { DICTIONARY_COLLISIONS, EXAMPLE_TOOLS } from "../../scripts/lib/attribution-patterns.ts";
import { scanText } from "../../scripts/lib/attribution-scan.ts";
import { checkJs } from "../../scripts/lib/dist-checks.ts";
import { verifiedWordlist, WORDLIST_MODULE_PATH, WORDLIST_PATH } from "../../scripts/lib/wordlist.ts";
import {
  blankDictionaryCollisions,
  sourceAttributionInput,
  verifiedWordData,
} from "../../scripts/lib/wordlist-attribution.ts";
import { generatedPassphraseInput } from "../e2e/generated-passphrase.ts";

const root = join(import.meta.dirname, "../..");
const wordData = verifiedWordData(root);
const name = EXAMPLE_TOOLS.find((tool) => tool.startsWith("Co") && tool.endsWith("pilot")) as string;
const word = name.toLowerCase();

test("only the exact two source paths receive authenticated data exemptions", () => {
  for (const file of [WORDLIST_PATH, WORDLIST_MODULE_PATH]) {
    const input = sourceAttributionInput(root, file, readFileSync(join(root, file), "utf8"));
    assert.deepEqual(scanText(file, input), []);
    if (file === WORDLIST_MODULE_PATH) assert.ok(input.includes("// EFF Large Wordlist"));
    assert.ok(input.includes("abacus"));
  }
  assert.ok(scanText("elsewhere", sourceAttributionInput(root, "other.ts", JSON.stringify(wordData))).length > 0);
});

test("bundle exemption covers only exact authenticated AST string literals", () => {
  const source = `const words = Object.freeze(${JSON.stringify(wordData)}.split(" "));`;
  assert.deepEqual(checkJs("words.js", source), []);
  assert.deepEqual(checkJs("words.js", `const words = Object.freeze(\`${wordData}\`.split(" "));`), []);
  assert.ok(checkJs("words.js", `const words = \`${wordData}\${"${1}"}\`;`).length > 0);
  for (const extra of [
    `\n// Built with ${name}`,
    `\nexport const credit = "${word}";`,
    `\nexport const credit = "\\u0043${name.slice(1)}";`,
  ])
    assert.ok(checkJs("words.js", source + extra).some((finding) => finding.problem.includes("attribution")));
  assert.ok(checkJs("words.js", `const words = ${JSON.stringify(wordData.replace("abacus", "abacut"))};`).length > 0);
  assert.ok(checkJs("words.js", `// ${JSON.stringify(wordData)}\nconst words = [];`).length > 0);
});

test("generated passphrases admit every separator mode and capitalization", () => {
  for (const text of [
    `abacus-${word}`,
    `Abacus-05-${word}`,
    `abacus05${word}`,
    `abacus${word}`,
    `abacus-${word}_abacus`,
    `abacus-05-${word}!07!abacus`,
  ])
    assert.deepEqual(scanText("output", generatedPassphraseInput(text)), []);
});

test("marked output does not admit tool credits or malformed passphrases", () => {
  for (const text of [
    `Generated by ${name}`,
    word,
    `abacus-5-${word}`,
    `abacus-000-${word}`,
    `abacus!05?${word}`,
    `abacus-${word}!07!abacus`,
    `abacus-05-${word}!07?abacus`,
    `notaword-${word}`,
  ])
    assert.ok(scanText("output", generatedPassphraseInput(text)).length > 0);
});

test("authenticated raw list flags exactly the explicit collision set", () => {
  const { raw } = verifiedWordlist(root);
  const flagged = raw
    .trimEnd()
    .split("\n")
    .map((line) => line.split("\t")[1] as string)
    .filter((entry) => scanText("dictionary data", entry).length > 0);
  assert.deepEqual(flagged, DICTIONARY_COLLISIONS);
  assert.equal(scanText("dictionary data", raw).length, DICTIONARY_COLLISIONS.length);
});

test("collision masking preserves every other word in dictionary data", () => {
  const vendorName = EXAMPLE_TOOLS.find((entry) => entry.startsWith("Cl") && entry.length === 6) as string;
  const text = `abacus ${word} ${vendorName.toLowerCase()} zone`;
  assert.equal(blankDictionaryCollisions(text), `abacus ${" ".repeat(word.length)} ${vendorName.toLowerCase()} zone`);
  assert.ok(scanText("dictionary data", blankDictionaryCollisions(text)).length > 0);
});
